### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-NSS#11]
Please improve the UI of the team page. Make it look attractive. For now you can use dummy images we will change it when we will get the particular images.

Don't forget to attach the screen shot of before and after

**Comment by EntwistleOx** [comment]
can i take this?

**Comment by Aniket762** [comment]
@EntwistleOx go for it !

**Comment by Dhruvibansal** [comment]
hey can i also contribute in this repo

**Comment by Aniket762** [comment]
Hey @Dhruvibansal, sorry but this issue has been assigned we have similar issue in another repo please check that out (https://github.com/Webwiznitr/Project-daffodil/issues/10).

We would love your contribution 😁

**Comment by EntwistleOx** [comment]
thank you, on it!
