### ISSUE TITLE
Make it responsive 

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-NSS#9]
Don't forget to add screen shots

**Comment by codybarr** [comment]
I can take this one ;)

**Comment by Aniket762** [comment]
@codybarr sure man go for it 💪

**Comment by KeshriAyushi22** [comment]
i can give it a try. please assign this to me @Aniket762

**Comment by Aniket762** [comment]
@KeshriAyushi22 it is made almost responsive you need to make minor changes in some pages ! 

Please share the before and after screenshots

**Comment by Dhruvibansal** [comment]
is it still available ?

**Comment by Aniket762** [comment]
Hey @Dhruvibansal sorry but this issue has been assigned we have similar issue in another repo please check that out (https://github.com/Webwiznitr/Project-daffodil/issues/10).

We would love your contribution 😁
